services:
  nginx:
    image: nginx:latest
    container_name: nginx-container-xss
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9003:80
    depends_on:
      - mysql
    networks:
      - internal
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container-xss
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - internal
  mysql:
    image: mysql:5.7
    container_name: mysql-container-xss
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqli
    networks:
      - internal
  bot:
    build:
      context: admin-bot/bot
      args:
        - BROWSER=chromium
    restart: always
    environment:
      APPNAME: Admin
      APPURL: http://nginx/
      APPURLREGEX: ^http(|s)://.*$
      APPFLAG: LKSPML{steal_cookies_using_xss_attack}
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
      DISPLAY: ""
    networks:
      - internal

networks:
  internal:
